---
abstract: 'Perl extension for getting the reftype of a scalar ref'
author:
  - 'Hao Wu <echowuhao@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.141520'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Scalar-Reftype
no_index:
  directory:
    - t
    - inc
requires: {}
version: '0.01'
